### ISSUE TITLE
Sentry datasource querying wrong Sentry URL

### ISSUE THREAD

**Issue by skygrammas** [grafana/sentry-datasource#258]
**What happened**:
Sentry data source is attempting to fetch data from an invalid host/URL. 

**What you expected to happen**:
Sentry data source to attempt to fetch data from the URL that is explicitly listed in the data source configuration.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Grafana using the [Grafana Operator](https://github.com/grafana/grafana-operator) v5.8.1 on Kubernetes.
2. Configure the Sentry data source in the Grafana Kubernetes custom resource (see snippet below for exact configuration).
3. In the Grafana UI, visit *Home > Connections > Data sources*.
4. Click the Sentry data source, then click *Explore data* in the top-right corner

**Screenshots, Recordings, and Configuration**

https://github.com/grafana/sentry-datasource/assets/23141825/e90a44fe-4f2b-494e-b568-f2e81aaccb6a

It is expected that the data source fetches data from `https://cruise.sentry.io/api/0/organizations/cruise/projects` instead of `https://cruise.sentry.iohttps//sentry.io/api/0/organizations/cruise/projects/` (which is not a valid host).

<img width="610" alt="Screenshot 2024-05-23 at 10 45 15 AM" src="https://github.com/grafana/sentry-datasource/assets/23141825/49dc7f7d-f5a7-4ac2-851c-2a0670597733">

The URL in the configuration of the data source is shown in the screen recording above. I will also share the codified configuration below:
```
- name: sentry 
  type: grafana-sentry-datasource
  access: proxy
  isDefault: false
  basicAuth: false
  jsonData:
    url: "https://cruise.sentry.io"
    orgSlug: "cruise"
  secureJsonData:
    authToken: "${SENTRY_TOKEN}"
  secrets:
    - name: sentry-token
      env: SENTRY_TOKEN
      targetPath: secureJsonData.authToken
      value: [redacted]
  plugins:
    - name: grafana-sentry-datasource
      version: 1.7.0
```

- Grafana version: 10.4.1
- Plugin version: 1.7.0
- Grafana platform: Kubernetes v1.27.11 via Grafana CR using the Grafana Operator v5.8.1
- User OS & Browser: MacOS 14.5 & Google Chrome
